### ISSUE TITLE
Does Not show CPU Temp

### ISSUE THREAD

**Issue by itisrj** [DanielStormApps/Fanny#10] opened 2017-03-11 04:04 UTC
![screen shot 2017-03-10 at 11 02 32 pm](https://cloud.githubusercontent.com/assets/26339245/23820415/d828d848-05e5-11e7-90cb-9af6f1c86641.png)
CPU Temperature reads 0.

**Comment by DanielStormApps** [comment] 2017-03-12 14:35
What model and year is your Mac?

**Comment by itisrj** [comment] 2017-03-12 15:34
21.5 in iMac 3.06 GHz intel core duo processor. (Late 2009)

**Comment by stilun** [comment] 2017-03-22 15:31
I have the same problem on my computer, a 21.5 inch iMac 3.06 GHz intel core duo processor (Late 2009) and macOS Sierra version 10.12.3.

**Comment by arpieb** [comment] 2017-07-09 00:45
I'm seeing the same behavior on a MacPro 5,1 Mid-2010, 2x3.46GHz Xeons running OSX 10.12.5.  I can confirm that the sensor wires are attached to the heatsink (just upgraded my CPUs) and was having the same behavior before the swap.

**Comment by Canuckx** [comment] 2017-08-01 23:57
I'll bump this thread.  
Same problem on a 21.5 inch iMac 3.06 GHz intel core duo processor (Late 2009) and macOS 10.12.6

**Comment by legendero** [comment] 2017-09-10 00:04
same here

**Comment by skizzums** [comment] 2017-09-15 08:59
same issue. Hackintosh running 4th gen Core i3. Running latest SMC that currently runs all the HW monitoring tools, looking for other temp tools because HW monitors showing varying inaccuracy to what the mobo is telling me in the bios. Very well could be a problem on my end which is causing the issue with your tool as well, but like others, your showing the connected fans and speeds perfectly, but on 0 degree on temps. Keep up the good work, like the simple design of your tool

**Comment by Magneticdud** [comment] 2017-10-10 17:42
Me too on iMac 11.2 with macOS 10.13

**Comment by dmyers** [comment] 2017-10-20 05:06
I had this issue on a 2009 Mac Pro too.

**Comment by shkesar** [comment] 2018-02-08 09:02
Same issue on iMac late 2009 27".

**Comment by DanielStormApps** [comment] 2019-09-22 05:47
Resolved in https://github.com/DanielStormApps/Fanny/commit/cec8011c7d7f9460afbb530b689594232208bad8 👍

**Closed by DanielStormApps** 2019-09-22 05:47 UTC
